scoreboard:
    lines:
    
    # Variables:
    # @h @m @s - Hours, minutes and seconds.
    # @d @w @g - Dragon, Wither and guardian colors.
    # @r - Current runner.
     
        title: "§4§lHardcore Chrono"
        line1:
        line2:
        line3:
        line4:
        line5:
        line6: